/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteDAO;

import PacoteModelo.Estoque;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class FrameVenda extends javax.swing.JFrame {

    /**
     * Creates new form FrameVenda
     */
    public FrameVenda() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLc = new javax.swing.JLabel();
        jBpesquisarN = new javax.swing.JButton();
        jLn = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLv = new javax.swing.JLabel();
        jLvalor = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLq = new javax.swing.JLabel();
        jLestoque = new javax.swing.JLabel();
        jLq2 = new javax.swing.JLabel();
        jTquantidade = new javax.swing.JTextField();
        jBpesquisarC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jBinserir = new javax.swing.JButton();
        jLcodC = new javax.swing.JLabel();
        jLnomeC = new javax.swing.JLabel();
        jTcodC = new javax.swing.JTextField();
        jTnomeC = new javax.swing.JTextField();
        jBpesquisarCliC = new javax.swing.JButton();
        jBpesquisarNomC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBremover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");

        jLc.setText("Código do Produto:");

        jBpesquisarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq1.png"))); // NOI18N
        jBpesquisarN.setText("Pesquisar Por Nome");
        jBpesquisarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarNActionPerformed(evt);
            }
        });

        jLn.setText("Nome do Produto:");

        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });

        jLv.setText("Valor Unitário:");

        jLq.setText("Quantidade em Estoque:");

        jLq2.setText("Quantidade de Produtos no Pedido:");

        jBpesquisarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq1.png"))); // NOI18N
        jBpesquisarC.setText("Pesquisar Por Código");
        jBpesquisarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarCActionPerformed(evt);
            }
        });

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTablePedido);

        jBinserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/inserir1.png"))); // NOI18N
        jBinserir.setText("Inserir");
        jBinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirActionPerformed(evt);
            }
        });

        jLcodC.setText("Código do Cliente:");

        jLnomeC.setText("Nome do Cliente:");

        jBpesquisarCliC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq1.png"))); // NOI18N
        jBpesquisarCliC.setText("Pesquisar Por Código");
        jBpesquisarCliC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarCliCActionPerformed(evt);
            }
        });

        jBpesquisarNomC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq1.png"))); // NOI18N
        jBpesquisarNomC.setText("Pesquisar Por Nome");
        jBpesquisarNomC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarNomCActionPerformed(evt);
            }
        });

        jLabel1.setText("___________________________________________________________________________________________________________________________");

        jBremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover1.png"))); // NOI18N
        jBremover.setText("Remover ");
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/venda1.png"))); // NOI18N
        jButton1.setText("Imprimir Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        jBvoltar.setText("Voltar");
        jBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLcodC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTcodC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBpesquisarCliC)
                        .addGap(12, 12, 12)
                        .addComponent(jLnomeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTnomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBpesquisarNomC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBpesquisarN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLvalor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBpesquisarC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLq2)
                                .addGap(18, 18, 18)
                                .addComponent(jTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jBinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBremover)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBvoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodC)
                    .addComponent(jTcodC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisarCliC)
                    .addComponent(jLnomeC)
                    .addComponent(jTnomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisarNomC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLn)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBpesquisarN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLc)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisarC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLv)
                    .addComponent(jLvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLestoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBinserir)
                        .addComponent(jBremover)
                        .addComponent(jLq2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jBvoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBpesquisarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarNActionPerformed
        Estoque p = new Estoque();
        EstoqueDAO pesq = new EstoqueDAO();
        p = pesq.consultarApProduto(jTnome.getText());
        
        if(p == null){
            JOptionPane.showMessageDialog(null, "Nome Incorreto!");
            jTnome.setText(null);
            jTcodigo.setText(null);
            jLvalor.setText(null);
            jLestoque.setText(null);
            jTquantidade.setText(null);
        }
        else{           
            jTcodigo.setText(String.valueOf(p.getCodigo())); 
            jLvalor.setText(String.valueOf(p.getValorUni()));
            jLestoque.setText(String.valueOf(p.getQuantidade())); 
            jBpesquisarC.setVisible(false);
        }        
    }//GEN-LAST:event_jBpesquisarNActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jBpesquisarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarCActionPerformed
        Estoque p = new Estoque();
        EstoqueDAO pesq = new EstoqueDAO();
        p = pesq.consultarProduto(Integer.parseInt(jTcodigo.getText()));
        
        if(p == null){
            JOptionPane.showMessageDialog(null, "Código Incorreto!");
            jTnome.setText(null);
            jTcodigo.setText(null);
            jLvalor.setText(null);
            jLestoque.setText(null);
            jTquantidade.setText(null);
        }
        else{           
            jTnome.setText(p.getNome());            
            jLvalor.setText(String.valueOf(p.getValorUni()));
            jLestoque.setText(String.valueOf(p.getQuantidade()));              
        }
    }//GEN-LAST:event_jBpesquisarCActionPerformed

    private void jBinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirActionPerformed
        double qa,qv,qn,v;
        v = 0;
        qa = Double.parseDouble(jLestoque.getText());
        qv = Double.parseDouble(jTquantidade.getText());
        
        if(qa == v){
            JOptionPane.showMessageDialog(null,"Não há " + jTnome.getText() + " no estoque!");
            jTnome.setText(null);
            jTcodigo.setText(null);
            jTquantidade.setText(null);
            jLvalor.setText(null);
            jLestoque.setText(null);
            jBpesquisarC.setVisible(true);
            jBpesquisarN.setVisible(true);
            jTnome.requestFocus();}
        
        else if(qa < qv){
            JOptionPane.showMessageDialog(null,"Quantidade especificada de " + jTnome.getText() + " é maior do que o total disponível no estoque!");
            jTquantidade.requestFocus();
    } 
           else{
         
        qn = qa - qv;   //subtração para definir o novo valor do estoque
        
        Estoque e = new Estoque();
        e.setQuantidade(qn);
        e.setCodigo(Integer.parseInt(jTcodigo.getText()));        
        
        EstoqueDAO c = new EstoqueDAO();
        c.qtdProduto(e);
        
        String nome = jTnome.getText().trim();
        String codigo = jTcodigo.getText().trim();
        String quantidade = jTquantidade.getText().trim();
        
        DefaultTableModel val = (DefaultTableModel) jTablePedido.getModel();
        
            val.addRow(new String [] {nome,codigo,quantidade}); //adiciona valores a tabela
        
        jTnome.setText(null);
        jTcodigo.setText(null);
        jTquantidade.setText(null);
        jLvalor.setText(null);
        jLestoque.setText(null);
        jBpesquisarC.setVisible(true);
        jBpesquisarN.setVisible(true);
        jTnome.requestFocus();}
 
    }//GEN-LAST:event_jBinserirActionPerformed

    private void jBpesquisarCliCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarCliCActionPerformed
        Estoque p = new Estoque();
        EstoqueDAO pesq = new EstoqueDAO();
        p = pesq.consultarCliente(Integer.parseInt(jTcodC.getText()));
        
        if(p == null){
            JOptionPane.showMessageDialog(null, "Código Incorreto!");
            jTnomeC.setText(null);
            jTcodC.setText(null);            
        }
        else{           
            jTnomeC.setText(p.getNome());             
        }
    }//GEN-LAST:event_jBpesquisarCliCActionPerformed

    private void jBpesquisarNomCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarNomCActionPerformed
        Estoque p = new Estoque();
        EstoqueDAO pesq = new EstoqueDAO();
        p = pesq.consultarApCliente(jTnomeC.getText());
        
        if(p == null){
            JOptionPane.showMessageDialog(null, "Nome Incorreto!");
            jTnomeC.setText(null);
            jTcodC.setText(null);            
        }
        else{           
            jTcodC.setText(String.valueOf(p.getCodigo()));
            jBpesquisarCliC.setVisible(false);
        }
    }//GEN-LAST:event_jBpesquisarNomCActionPerformed

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
         DefaultTableModel tableModel = (DefaultTableModel) jTablePedido.getModel();//Pega o modelo
         int row = jTablePedido.getSelectedRow(); //Seleciona a linha 
         String c,q,atual;
         
         c = tableModel.getValueAt(row, 1).toString(); //Pegar código
         q = tableModel.getValueAt(row, 2).toString(); //Pegar quantidade
         
         //double qA = Double.parseDouble(q), atualA = Double.parseDouble(atual),totalA = Double.parseDouble(total) ;
        Estoque e = new Estoque();
        EstoqueDAO pesq = new EstoqueDAO();
        e = pesq.consultarProduto(Integer.parseInt(c));
        atual = (String.valueOf(e.getQuantidade()));
        double qA = Double.parseDouble(q), atualA = Double.parseDouble(atual),total;
        total = atualA + qA;                
        
        e.setQuantidade(total); //Passando os valores para a alteração no produto
        e.setCodigo(Integer.parseInt(c));      
        
        pesq.qtdProduto(e);
      
        ((DefaultTableModel) jTablePedido.getModel()).removeRow(jTablePedido.getSelectedRow());
        
    }//GEN-LAST:event_jBremoverActionPerformed

    private void jBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarActionPerformed
        FrameInicial a = new FrameInicial();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBvoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Pedido Finalizado Com Sucesso!"+"\nNome do Cliente: "+jTnomeC.getText()+
                                       "\nCódigo do Cliente: "+jTcodC.getText());
        
        while (jTablePedido.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) jTablePedido.getModel()).removeRow(0);  
       } 
        
        jTnomeC.setText(null);
        jTcodC.setText(null);
        jTnome.setText(null);
        jTcodigo.setText(null);
        jTquantidade.setText(null);
        jLvalor.setText(null);
        jLestoque.setText(null);
        jBpesquisarC.setVisible(true);
        jBpesquisarN.setVisible(true);
        jBpesquisarCliC.setVisible(true);
        jBpesquisarNomC.setVisible(true);
        jTcodC.requestFocus();   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBinserir;
    private javax.swing.JButton jBpesquisarC;
    private javax.swing.JButton jBpesquisarCliC;
    private javax.swing.JButton jBpesquisarN;
    private javax.swing.JButton jBpesquisarNomC;
    private javax.swing.JButton jBremover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jBvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLc;
    private javax.swing.JLabel jLcodC;
    private javax.swing.JLabel jLestoque;
    private javax.swing.JLabel jLn;
    private javax.swing.JLabel jLnomeC;
    private javax.swing.JLabel jLq;
    private javax.swing.JLabel jLq2;
    private javax.swing.JLabel jLv;
    private javax.swing.JLabel jLvalor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JTextField jTcodC;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTnomeC;
    private javax.swing.JTextField jTquantidade;
    // End of variables declaration//GEN-END:variables
}
